### ISSUE TITLE
Problem component 2 has no name

### ISSUE THREAD

**Issue by hwborchers** [anqif/CVXR#17]
When calling `result <- solve(problem)` on a CVXR-defined problem, the structure of the result has an unnamed component that probably should be called `result$solution` or similar.

    > result <- solve(problem)
    > result
    $status
    [1] "optimal"

    $value
    [1] 97.84759

    $`2`
                 [,1]
     [1,] -3.91968871
     [2,] -3.01170409
     ...

    $solver
    [1] "ECOS"
    ...

The solution can be retrieved with `result[[2]]`, but I assume that is not what was intended.

**Comment by bnaras** [comment]
That is by design. Those numbers `2` etc. are ids that are generated internally and not for general use. That is why the function `result$getValue()` is provided to get at variable values easily.
