### ISSUE TITLE
small values for LASSO

### ISSUE THREAD

**Issue by liyi-1989** [anqif/CVXR#19]
I tried a test case with a loss of matrix Frobenius norm plus ($\lambda$ times) a penalty of l1 norm, like the normal LASSO case ($\min||X-A||_F+\lambda||X||_1$). I found the result, with a proper $\lambda$, the result has many small values (less than 1e-10) rather than zeros. (I also tried increase the $\lambda$, the values are getting smaller but never become exactly zeros). So it cannot get exactly sparse solution as the theoretical results asserts. 

Is this a common problem in numerical optimization of l1 norm (even though theory says it is sparse, the numerical result only get very small number)? As I remembered, source code in package like glmnet also use a manually truncation step in the end of the code. So, do you suggest to truncate the results when it is extremely small, or try larger penalties? or is there any other solutions? (or I can be wrong in my simulation.)

**Comment by brianborchers** [comment]
Yes, this is a very common problem, and yes, the standard approach is to round those small values down to 0.

**Comment by liyi-1989** [comment]
Thank you so much! @brianborchers

**Comment by zgao-cuhk** [comment]
Hi @liyi-1989,

As @brianborchers said, it is a common problem as long as you implement Lasso by solving the convex optimization problem numerically. It is the same when you use other solvers, like Rmosek.

You mentioned that glmnet trims small coefficients to 0 by some threshold. I am wondering if you have any idea how they set the threshold. Thanks a lot.

**Comment by bnaras** [comment]
I can only guess a bit, but perhaps this bit of MORTAN has something to do with it. 
<code>
subroutine get_int_parms(sml,eps,big,mnlam,rsqmax,pmin,exmx);
implicit double precision(a-h,o-z);
data sml0,eps0,big0,mnlam0,rsqmax0,pmin0,exmx0
   /1.0e-5,1.0e-6,9.9e35,5,0.999,1.0e-9,250.0/;
sml=sml0; eps=eps0; big=big0; mnlam=mnlam0; rsqmax=rsqmax0;
pmin=pmin0; exmx=exmx0;
return;
<\code>

**Comment by bnaras** [comment]
I can only guess, but this bit if MORTRAN might give a clue.

```
subroutine get_int_parms(sml,eps,big,mnlam,rsqmax,pmin,exmx);
implicit double precision(a-h,o-z);
data sml0,eps0,big0,mnlam0,rsqmax0,pmin0,exmx0
   /1.0e-5,1.0e-6,9.9e35,5,0.999,1.0e-9,250.0/;
sml=sml0; eps=eps0; big=big0; mnlam=mnlam0; rsqmax=rsqmax0;
pmin=pmin0; exmx=exmx0;
return;
```

**Comment by liyi-1989** [comment]
@zgao-cuhk Sorry I cannot find it now. As I remembered (I viewed several lasso-type packages last year), it is something related to the machine precision (truncated with eps/or some function of eps).
