### ISSUE TITLE
CVXR Feasibility Problem

### ISSUE THREAD

**Issue by benubah** [anqif/CVXR#20]
Hi,

Can CVXR solve feasibility problems like those found here: https://stanford.edu/class/ee363/notes/lmi-cvx.pdf

An example using CVX is:

    cvx_begin sdp
     variable P(n,n) symmetric
     A'*P + P*A <= -eye(n)
     P >= eye(n)
    cvx_end
As seen above, there is no minimization or maximization; just looking a `P` that satisfies the constraints.
If this is possibly using CVXR, which function could be used for it.
If no, can this functionality be added to the CVXR package?

Thank you

**Comment by anqif** [comment]
You can simply set the objective function to a constant, e.g.
P <- Symmetric(n)
obj <- Minimize(0)
constr <- list(t(A) %*% P + P %*% A <= -diag(n), P >= diag(n))
solve(Problem(obj, constr))

**Comment by benubah** [comment]
Thank you for your prompt response.
I understand this clearly now.
Before this thread is closed: can you please clarify in this LMI scenario, the most appropriate to be used between `<=` and `%<<%`

i.e.

`constr <- list((t(A) %*% P + P %*% A) %<<% -diag(n), P %>>% diag(n))`

and

`constr <- list((t(A) %*% P + P %*% A) <= -diag(n), P >= diag(n))`

They yield different results. As this is an LMI, which operator should be used?

Thank you

**Comment by anqif** [comment]
The expression `A >= B` constrains every element of A to be greater-than-or-equal-to its corresponding element in B, while `A %>>% B` restricts (A - B) to be positive semidefinite. You can find all this in the CVXR documentation.
