### ISSUE TITLE
How to specific fit CVXR in integer constraint and quadratic object?

### ISSUE THREAD

**Issue by harryprince** [anqif/CVXR#36]
I have seen CVXPY can specific `w = Variable(10, integer = True)` to bound variable w in integer mode, How I can do it in CVXR?

I am trying to apply a clustering algorithm and minimize the modularity loss, sincerely need your help.

**Comment by bnaras** [comment]
What you describe is the recent CVXPY 1.0 syntax. CVXR 0.99 is based on the pre-1.0 syntax and will catch up to the 1.0 at that version. The ingredients are there in CVXR, however. See: 

http://www.cvxpy.org/updates/index.html#updates

To be specific, use 
```{r}
w <- Integer(10)
```
