### ISSUE TITLE
Installation of package ‘CVXR’ had non-zero exit status

### ISSUE THREAD

**Issue by ds2010** [anqif/CVXR#48]
Hi, I tried to use `install.packages('CVXR')`  to install the CVXR package on linux-gnu, but I was failed. The showed errors are as follows. The r verion I used is 3.4.1 (2017-06-30).

* compilation aborted for RcppCVXcanon.cpp (code 2) make: *** [RcppCVXcanon.o] Error 2
ERROR: compilation failed for package ‘CVXR’
* removing ‘/scratch/work/XXXX/R/3.4.1/CVXR’
* The downloaded source packages are in
                ‘/tmp/Rtmpbl4UzJ/downloaded_packages’
* Warning message:
   In install.packages("CVXR", repos = "https://CRAN.R-project.org") :
   installation of package ‘CVXR’ had non-zero exit status

So, Could you give me some help or suggestions? Thanks in advance.

**Comment by bnaras** [comment]
Without the full details of what the error is, it is hard to provide help. But I would suggest that you upgrade your R version which is almost 2 years old. Then, also make sure you have the compiler tool chain. On Debian linux platforms, 
```
apt-get install r-base-dev
``` 
will ensure that.

**Comment by ds2010** [comment]
Thank you so much. After upgrading the R version, I successfully installed the CVXR package. Now, it works well.
